apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app-secretless
  name: demo-app-secretless
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-secretless
  template:
    metadata:
      labels:
        app: demo-app-secretless
    spec:
      serviceAccountName: demo-app-secretless-sa
      containers:
        - image: bnasslahsen/conjur-spring-boot-demos
          name: demo-app-secretless
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: conjur-connect-secretless
          ports:
            - containerPort: 8080
        - name: configurator
          image: cyberark/secretless-broker
          imagePullPolicy: IfNotPresent
          args: ["-f", "/etc/secretless/secretless.yml"]
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - mountPath: /etc/secretless
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: secretless-config-mysql
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-secretless
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32087
  selector:
    app: demo-app-secretless
